### ISSUE TITLE
The console doesn't aways scroll to bottom while new logs are being output

### ISSUE THREAD

**Issue by wong2** [rafaelrozon/react-storybook-console#1]
Hi, thanks for the project! Sometimes, the console would stop in a position, and even if there are more logs being output, it won't scroll to the bottom.

I'm using the latest version of `react-storybook-console` and Chrome

**Comment by rafaelrozon** [comment]
Hi, @wong2. Thank you for your feedback. I'll try to replicate the problem and fixed it. 
Thanks.

**Comment by rafaelrozon** [comment]
Closing this. The project is not being maintained for a long time and there's an official version.
