### ISSUE TITLE
Contact the maintainers of storybook

### ISSUE THREAD

**Issue by ndelangen** [rafaelrozon/react-storybook-console#2]
Hey! wow what an awesome addon!,
This deserves far more promotion! 
I'd be happy to receive a PR on documentation featuring this for example!

Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by rafaelrozon** [comment]
Hello, @ndelangen. 

Thank you so much for the invite. Sorry for the late reply. I'll submit a PR tonight. 

Have a great week ahead.
