### ISSUE TITLE
Not intercepting prop-type warnings

### ISSUE THREAD

**Issue by bholloway** [rafaelrozon/react-storybook-console#3]
Firstly awesome add-on 👍. It is great not having to have the console open.

Maybe I have it misconfigured but the `react-storybook-console` is not catching runtime prop-type warnings in development. Definitely that would be nice to have since I need to keep the console open otherwise.

**As standard**
```javascript
storiesOf('MyComponent', module)
    .addDecorator(StorybookConsole)
    .add('do stuff', () => { ...... });
```
1. My story does `log.warn()` because of prop-type mismatch
2. My story didMount
3. The `react-storybook-console` component didMount and starts intercepting `window.console.*`

**My 2minute hack**
```javascript
const withDelay = storyFn => React.createElement(
  class Delay extends React.Component {
    constructor(props) {
      super(props);
      this.state = {mounted: false};
    }

    componentDidMount() {
      this.setState({mounted: true});
    }

    componentWillUnmount() {
      this.setState({mounted: false});
    }

    render() {
      return this.state.mounted ? storyFn() : <div />;
    }
  }
);
```
and then
```javascript
storiesOf('MyComponent', module)
    .addDecorator(withDelay)
    .addDecorator(StorybookConsole)
    .add('do stuff', () => { ...... });
```
1. The `Delay` wrapper renders a placeholder empty `div`
2. The `react-storybook-console` component didMount and starts intercepting `window.console.*`
2. The `Delay` wrapper sets state to `mounted=true`
3. The `Delay` wrapper re-renders (with new state) the actual `storyFn()`
4. My story does `log.warn()` because of prop-type mismatch

This only works where `.addDecorator(withDelay)` appears  _before_ `.addDecorator(StorybookConsole)`. Presumably this is the order of decorators which puts `StorybookConsole` on the outside 😉 

**Conclusions**

The hack seems to be reasonable in terms of the React methodology.

I guess it is a question whether it is compatible with `storybook` internals. I would hope that decorating a story in this way doesn't produce any unwanted side effects. Certainly `storybook-knobs` seem (at first glance) to be working correctly.

Is this something that could be absorbed into `react-storybook-console`?

**Comment by rafaelrozon** [comment]
hi @bholloway. Thank you reporting the issue and for such a good explanation. I'll investigate more and possibly incorporate your suggestions. Sorry I didn't see this before.

**Comment by rafaelrozon** [comment]
Closing this. The project is not being maintained for a long time and there's an official version.
